name: Compile Code

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Run hello world
      run: echo Hello World
