name: Integration Tests

on:
  pull_request:
    branches: [main]

jobs:
  run-spring-boot:
    name: Run Spring Boot and Test
    runs-on: ubuntu-latest
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v3
    # Install Java JDK version 17
    - name: Install Java 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    # Setup MySQL
    - name: Setup MySQL
      run: sudo systemctl start mysql.service
    # Create csye6225 directory
    - name: Create Logging Directory and log files
      run: sudo mkdir --parents /var/log/csye6225
    # Create errors.log file
    - name: Create errors.log
      run: sudo touch /var/log/csye6225/errors.log
    # Create info.log file
    - name: Create info.log
      run: sudo touch /var/log/csye6225/info.log
    # Grant write access for log files
    - name: Grant write access
      run: |
        sudo chmod ugo+wx /var/log/csye6225/errors.log
        sudo chmod ugo+wx /var/log/csye6225/info.log
    # Start spring boot and run integration tests
    - name: Run Spring Boot
      run: | 
        mvn spring-boot:run -Dspring.datasource.url=jdbc:mysql://localhost:3306/clouddb?createDatabaseIfNotExist=true -Dspring.datasource.username=${{secrets.MYSQL_USERNAME}} -Dspring.datasource.password=${{secrets.MYSQL_PASSWORD}} -Dspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver -Dspring.jpa.hibernate.ddl-auto=update -Dspring.datasource.hikari.connection-timeout=20000 &
        sleep 60
        mvn test
        