name: Packer Validate

on:
  pull_request:
    branches: [main]

jobs:
    packer-validate:
        name: Packer Validate
        runs-on: ubuntu-latest
    
        services:
          # setup mysql service and perform health check
          mysql:
            image: mysql:8.0
            env:
              MYSQL_DATABASE: clouddb
              MYSQL_USER: ${{secrets.MYSQL_USERNAME}}
              MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
              MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
            ports:
              - 3306:3306
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
        steps:
          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - name: Checkout code
          uses: actions/checkout@v3
          # Install Java JDK version 17
        - name: Install Java 17
          uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: temurin
          # Install MySQL
        - name: Install MySQL
          run: sudo apt-get install -y mysql-client
          # Build Spring boot project and remove old artifacts
        - name: Build project
          run: mvn clean package -DskipTests
          # Setup Packer
        - name: Setup Packer
          uses: hashicorp/setup-packer@main
        # Initialise Packer
        - name: Packer init
          run: packer init ./main.pkr.hcl
        # Format packer files
        - name: Packer format
          run: packer fmt -check ./main.pkr.hcl
        # Validate Packer Files
        - name: Packer validate
          run: packer validate ./main.pkr.hcl
